

clusterName: voyager-cluster
karpenterVersion: v0.33.0
karpenterApiVersion: karpenter.sh/v1

serviceAccount:
  create: true
  name: karpenter
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::009537862357:role/karpenter-controller-role

settings:
  aws:
    defaultInstanceProfile: karpenter-node-instance-profile
    clusterEndpoint: https://0A70DAC60A645C539982DB2CFAE16624.gr7.ap-northeast-2.eks.amazonaws.com
    roleArn: arn:aws:iam::009537862357:role/karpenter-controller-role

replicas: 1
image:
  repository: public.ecr.aws/karpenter/controller
  tag: v0.33.0

controller:
  args:
    - --cluster-name=voyager-cluster